spring.application.name=ecom-proj
spring.datasource.url=jdbc:postgresql://localhost:5432/Ecommerce-Project
spring.datasource.username=fakeUsername
spring.datasource.password=fakePassword
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
